# goal
int32[] target_ids

---
# result
bool finished
string status_message   #  e.g., "Exploration ended. 3 Apriltags found"
apriltag_ros/AprilTagDetection[] detected_tags

---
# feedback
string robot_status # Current robot status: "Moving," "Scanning," etc.
apriltag_ros/AprilTagDetection current_detection
float32 progress_status         # 1  tags found

